Add database as optional argument

diff --git a/uniortho b/uniortho
--- a/uniortho
+++ b/uniortho
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.1.0 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.6 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -69,7 +69,7 @@ uniortho_run_usage() {
   echo
 
   printf "%s\n" "$(bold "Usage:")"
-  printf "  uniortho run SPECIES [OPTIONS]\n"
+  printf "  uniortho run SPECIES [DATABASE] [OPTIONS]\n"
   printf "  uniortho run --help | -h\n"
   echo
 
@@ -138,6 +138,11 @@ uniortho_run_usage() {
     printf "    name of the species, leading with the s__ (using gtdb taxonomy)\n"
     echo
 
+    # :argument.usage
+    printf "  %s\n" "$(blue "DATABASE")"
+    printf "    optional user supplied BLAST database, if not supplied, the pipeline will\n    use the nt database.\n"
+    echo
+
   fi
 }
 
@@ -157,7 +162,7 @@ uniortho_test_usage() {
   echo
 
   printf "%s\n" "$(bold "Usage:")"
-  printf "  uniortho test [OPTIONS]\n"
+  printf "  uniortho test [DATABASE] [OPTIONS]\n"
   printf "  uniortho test --help | -h\n"
   echo
 
@@ -174,6 +179,14 @@ uniortho_test_usage() {
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
     printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "$(bold "Arguments:")"
+
+    # :argument.usage
+    printf "  %s\n" "$(blue "DATABASE")"
+    printf "    optional user supplied BLAST database, if not supplied, the pipeline will\n    use the nt database.\n"
     echo
 
   fi
@@ -208,7 +221,9 @@ inspect_args() {
   if ((${#args[@]})); then
     readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
     echo args:
-    for k in "${sorted_keys[@]}"; do echo "- \${args[$k]} = ${args[$k]}"; done
+    for k in "${sorted_keys[@]}"; do
+      echo "- \${args[$k]} = ${args[$k]}"
+    done
   else
     echo args: none
   fi
@@ -226,9 +241,19 @@ inspect_args() {
     readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
     echo
     echo deps:
-    for k in "${sorted_keys[@]}"; do echo "- \${deps[$k]} = ${deps[$k]}"; done
+    for k in "${sorted_keys[@]}"; do
+      echo "- \${deps[$k]} = ${deps[$k]}"
+    done
   fi
 
+  if ((${#env_var_names[@]})); then
+    readarray -t sorted_names < <(printf '%s\n' "${env_var_names[@]}" | sort)
+    echo
+    echo "environment variables:"
+    for k in "${sorted_names[@]}"; do
+      echo "- \$$k = ${!k:-}"
+    done
+  fi
 }
 
 # :command.user_lib
@@ -426,16 +451,29 @@ dgenomes=$1/fnas
 uqgenes=$1/uniquegenes.tsv
 dout=$1/blast
 threads=$2
+blastdb=$3
 
 mkdir -p $dout
 
-echo "$(green Running blast against nt database)"
-tail -n +2 $uqgenes |
-cut -d ' ' -f 3 |
-awk -v d="$din/" '$0='d'$0".fasta"' |
-xargs cat |
-blastn -query - -db nt -remote \
- -out $dout/results -outfmt 6
+if [[ "$blastdb" != false ]] ; then
+    echo "$(green Running blast against $blastdb database)"
+    tail -n +2 $uqgenes |
+    cut -d ' ' -f 3 |
+    awk -v d="$din/" '$0='d'$0".fasta"' |
+    xargs cat |
+    blastn -query - -db $blastdb \
+    -out $dout/results -outfmt 6
+
+else
+    echo "$(green Running blast against nt database)"
+    tail -n +2 $uqgenes |
+    cut -d ' ' -f 3 |
+    awk -v d="$din/" '$0='d'$0".fasta"' |
+    xargs cat |
+    blastn -query - -db nt -remote \
+    -out $dout/results -outfmt 6
+
+fi
 
 }
 
@@ -534,6 +572,7 @@ uniortho_run_command() {
   cpus=${args[--threads]}
   ani_threshold=${args[--ani]}
   blast_check=${args[--blast]}
+  blast_db=${args[database]}
 
   # Add s__ to species if absent
   if [[ $species != s__* ]]; then
@@ -581,7 +620,7 @@ uniortho_run_command() {
   fetch_genes $outf
 
   if [[ $blast_check == 1 ]]; then
-      run_blast_check $outf $cpus
+      run_blast_check $outf $cpus $blast_db
       script_in_bin "process_blast_check.py"
       $HOME/.local/bin/process_blast_check.py $outf/blast/results $outf/uniquegenes.tsv $outf
   fi
@@ -592,12 +631,13 @@ uniortho_run_command() {
 uniortho_test_command() {
   # src/test_command.sh
   blast_check=${args[--blast]}
+  blast_db=${args[database]}
   outf="test_out"
 
   if [[ $blast_check == 1 ]]; then
       script_in_bin "process_blast_check.py"
       if [[ ! -s "test_out/blast/results" ]]; then
-      uniortho run "s__Sumerlaea chitinivorans" -C 10 -o $outf --blast
+      uniortho run "s__Sumerlaea chitinivorans" -C 10 -o $outf --blast "$blast_db"
       else
 
           echo "$(blue Blast results already exist. Skipping blast)"
@@ -863,6 +903,10 @@ uniortho_run_parse_requirements() {
 
           args['species']=$1
           shift
+        elif [[ -z ${args['database']+x} ]]; then
+
+          args['database']=$1
+          shift
         else
           printf "invalid argument: %s\n" "$key" >&2
           exit 1
@@ -875,7 +919,7 @@ uniortho_run_parse_requirements() {
 
   # :command.required_args_filter
   if [[ -z ${args['species']+x} ]]; then
-    printf "missing required argument: SPECIES\nusage: uniortho run SPECIES [OPTIONS]\n" >&2
+    printf "missing required argument: SPECIES\nusage: uniortho run SPECIES [DATABASE] [OPTIONS]\n" >&2
     exit 1
   fi
 
@@ -931,8 +975,14 @@ uniortho_test_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key" >&2
-        exit 1
+        if [[ -z ${args['database']+x} ]]; then
+
+          args['database']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
 
         ;;
 
@@ -954,6 +1004,7 @@ run() {
   declare -A args=()
   declare -A deps=()
   declare -a other_args=()
+  declare -a env_var_names=()
   declare -a input=()
   normalize_input "$@"
   parse_requirements "${input[@]}"
