Add example run on underrepresented species to test dependency installation

diff --git a/uniortho b/uniortho
--- a/uniortho
+++ b/uniortho
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.1.0 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.6 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -163,7 +163,9 @@ inspect_args() {
   if ((${#args[@]})); then
     readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
     echo args:
-    for k in "${sorted_keys[@]}"; do echo "- \${args[$k]} = ${args[$k]}"; done
+    for k in "${sorted_keys[@]}"; do
+      echo "- \${args[$k]} = ${args[$k]}"
+    done
   else
     echo args: none
   fi
@@ -181,9 +183,19 @@ inspect_args() {
     readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
     echo
     echo deps:
-    for k in "${sorted_keys[@]}"; do echo "- \${deps[$k]} = ${deps[$k]}"; done
+    for k in "${sorted_keys[@]}"; do
+      echo "- \${deps[$k]} = ${deps[$k]}"
+    done
   fi
 
+  if ((${#env_var_names[@]})); then
+    readarray -t sorted_names < <(printf '%s\n' "${env_var_names[@]}" | sort)
+    echo
+    echo "environment variables:"
+    for k in "${sorted_names[@]}"; do
+      echo "- \$$k = ${!k:-}"
+    done
+  fi
 }
 
 # :command.user_lib
@@ -460,22 +472,16 @@ uniortho_run_command() {
   fi
 
   # TODO: Add to path and call from there
-  ./src/lib/filter_unique_genes.R $outf/pan/pangenome.tsv $outf/ani.af $outf
+  if [[ ! -s $HOME/.local/bin/uo_filter_unique_genes.R ]]; then
+      echo "uo_filter_unique_genes.R not found in $HOME/.local/bin."
+      echo "Please add the script to your path, for example with"
+      echo "ln -s $PWD/src/lib/uo_filter_unique_genes.R $HOME/.local/bin"
+      exit 1
+  fi
+
+  $HOME/.local/bin/uo_filter_unique_genes.R $outf/pan/pangenome.tsv $outf/ani.af $outf
   fetch_genes $outf
 
-  #if (( $SECONDS > 3600 )) ; then
-  #	    let hours=SECONDS/3600
-  #	        let minutes=(SECONDS%3600)/60
-  #		    let seconds=(SECONDS%3600)%60
-  #		        echo "Completed in $hours hour(s), $minutes minute(s) and $seconds second(s)"
-
-  #		elif (( $SECONDS > 60 )) ; then
-  #			    let minutes=(SECONDS%3600)/60
-  #			        let seconds=(SECONDS%3600)%60
-  #				    echo "Completed in $minutes minute(s) and $seconds second(s)"
-  #			    else
-  #				        echo "Completed in $SECONDS seconds"
-  #fi
 }
 
 # :command.parse_requirements
@@ -724,6 +730,7 @@ run() {
   declare -A args=()
   declare -A deps=()
   declare -a other_args=()
+  declare -a env_var_names=()
   declare -a input=()
   normalize_input "$@"
   parse_requirements "${input[@]}"
